import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import {NextFont} from "next/dist/compiled/@next/font";

const montserrat: NextFont = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
